version: '3'
services:
  mysql-db:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ams_shop
    ports:
      - "3306:3306"
    build:
      context: ./mysql
      dockerfile: Dockerfile

  app:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 12345
      DB_DATABASE: ams_shop
