version: '3'
services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ams_shop
    ports:
      - "3306:3306"

  nestjs-app:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 12345
      DB_DATABASE: ams_shop
