name: CI/CD nestjs

on:
  push:
    branches:
      - "master"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: | 
          set -x
          IMAGE_TAG=$(git rev-parse --short HEAD)
          DOCKER_IMAGE_NAME="thinhphamndtdtu/shop-service-app"
          docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG .
          docker tag $DOCKER_IMAGE_NAME:$IMAGE_TAG $DOCKER_IMAGE_NAME:latest
          docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
          docker push $DOCKER_IMAGE_NAME:latest

      - name: Deloy to EC2
        uses: appleboy/ssh-action@v0.4.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_POST }}
          script: |
            cd /home/ubuntu/dev/backend
            docker-compose down
            docker-compose pull
            docker-compose up -d
